# Generated by Django 3.2 on 2021-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('author', models.CharField(max_length=122)),
                ('genre', models.CharField(max_length=100)),
                ('issued_to', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
            ],
        ),
    ]
