# Generated by Django 3.2 on 2021-05-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_auto_20210520_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ebook',
            field=models.FileField(upload_to='media'),
        ),
    ]
